#' Evaluate minimum signal count within each dilution series
#'
#' @description
#' Checks whether each feature-specific dilution or concentration series
#' contains a sufficient number of valid (non-missing) observations for
#' downstream modelling.
#'
#' Feature-series containing fewer than `MIN_FEATURE` observations are
#' flagged, excluded from subsequent analysis, and annotated accordingly.
#'
#' @details
#' For each feature-batch combination (`groupIndices`), the number of
#' non-missing values in the specified response variable is counted.
#'
#' Series failing the minimum requirement are:
#' \itemize{
#'   \item Marked as `"notEnoughPeaks"` in the `Comment` column
#'   \item Assigned the colour `"grey"`
#'   \item Excluded from further processing by setting the selected
#'         response variable to `NA`
#' }
#'
#' Series meeting the criterion are labelled `"EnoughPeaks"`.
#'
#' @param DAT A data.table containing feature-wise dilution or concentration
#' series.
#'
#' @param MIN_FEATURE Integer. Minimum number of non-missing observations
#' required for a series to be considered suitable for linearity assessment.
#'
#' @param step Integer. Processing step identifier used to create
#' step-specific output column names.
#'
#' @param y Character. Name of the response variable to evaluate
#' (e.g. `"Y"` or `"Y_trans"`).
#'
#' @return A list containing:
#' \describe{
#'   \item{filteredData}{Updated input data table with annotations and excluded observations.}
#'
#'   \item{summaryData}{Summary table containing the number of valid observations per feature-series and the corresponding pass/fail classification.}
#' }
#'
#' @examples
#' \dontrun{
#' res <- countMinimumValue(
#'   DAT = dat,
#'   MIN_FEATURE = 6,
#'   step = 1,
#'   y = "Y"
#' )
#' }
#'
#' @keywords internal
#' @import data.table
countMinimumValue <- function(DAT, MIN_FEATURE = parent.frame()$MIN_FEATURE, step, y){

  stopifnot(exprs ={"Parameter MIN_FEATURE needs to be greater or equal than 3" = MIN_FEATURE >= 3})

  dat <- data.table::data.table(DAT)

  #N <- paste0("N_",step)
  #enoughPeaks <- paste("enoughPeaks_",step)
  dat <- unique(dat[, N := sum(!is.na(get(y))),groupIndices][ , enoughPeaks := ifelse( N >= MIN_FEATURE, TRUE, FALSE)#,
                                                     #Comment = ifelse( N >= MIN_FEATURE, "EnoughPeaks", "notEnoughPeaks")
                                                     ][
                                                       ,list(groupIndices,Feature_ID, Batch, N, enoughPeaks)])

  DAT$color[DAT$groupIndices %in% dat$groupIndices[dat$enoughPeaks %in% FALSE]] <- "grey"
  DAT$Comment[DAT$groupIndices %in% dat$groupIndices[dat$enoughPeaks %in% FALSE]] <- unlist(apply(cbind(DAT$Comment[DAT$groupIndices %in% dat$groupIndices[dat$enoughPeaks %in% FALSE]], "notEnoughPeaks"), 1, function(x) paste(x[!is.na(x)], collapse = "_")))
  DAT$Comment[DAT$groupIndices %in% dat$groupIndices[dat$enoughPeaks %in% TRUE]] <- unlist(apply(cbind(DAT$Comment[DAT$groupIndices %in% dat$groupIndices[dat$enoughPeaks %in% TRUE]], "EnoughPeaks"), 1, function(x) paste(x[!is.na(x)], collapse = "_")))
  DAT[[y]][DAT$groupIndices %in% dat$groupIndices[dat$enoughPeaks %in% FALSE]] <- NA

  colnames(dat)[which(colnames(dat) %in% "N")] <- paste0("N_",step)
  colnames(dat)[which(colnames(dat) %in% "enoughPeaks")] <- paste0("enoughPeaks_",step)

    return(list(DAT, dat))
}

#' Summarise and validate filtering results
#'
#' @description
#' Evaluates the impact of a filtering step on the dataset by comparing
#' the number of remaining compounds, dilution/concentration series,
#' and batches before and after filtering.
#'
#' The function generates log messages describing the number of removed
#' feature-series and ensures that at least one valid feature and one
#' valid dilution series remain for further processing.
#'
#' @details
#' The function compares the status columns generated by
#' \code{countMinimumValue()} between two consecutive workflow steps.
#'
#' Feature-series failing the current filtering criterion are separated
#' into a cutoff dataset, while all remaining valid series are retained
#' for downstream analysis.
#'
#' An error is raised if all compounds or all dilution/concentration
#' series have been removed.
#'
#' @param step Integer. Current workflow step number.
#'
#' @param processingGroup Data table containing feature-series summary
#' information.
#'
#' @param processingFeature Data table containing signal-level information.
#'
#' @param Compounds Character string used for reporting compound counts.
#'
#' @param Dilutions Character string used for reporting dilution counts.
#'
#' @param Series Character string used for reporting series counts.
#'
#' @param Signals Character string used for reporting signal counts.
#'
#' @param MIN_FEATURE Integer. Minimum number of signals required per series.
#'
#' @return A list containing:
#' \describe{
#'   \item{filteredData}{Filtered signal-level dataset containing only valid
#'   feature-series.}
#'
#'   \item{removedData}{Dataset containing removed feature-series.}
#' }
#'
#' @examples
#' \dontrun{
#' res <- checkLength(
#'   step = 2,
#'   processingGroup = processingGroup,
#'   processingFeature = processingFeature,
#'   Compounds = "features",
#'   Series = "dilution series",
#'   MIN_FEATURE = 6
#' )
#' }
#'
#' @keywords internal
checkLength <- function(step, processingGroup, processingFeature, Compounds,
                        Dilutions, Series, Signals,
                        MIN_FEATURE){
  peaksOld <- ifelse(step > 1, paste0("enoughPeaks_", step-1), "enoughPeaks")

  peaksNew <- paste0("enoughPeaks_", step)

  nCompoundsOld <- data.table::uniqueN(processingGroup[get(peaksOld) %in% TRUE], by = c("Feature_ID"))
  nReplicatesOld <- data.table::uniqueN(processingFeature[color %in% "black"], by = c("Batch"))
  nSeriesOld <- data.table::uniqueN(processingGroup[get(peaksOld) %in% TRUE], by = c("groupIndices"))

  nCompoundsNew <- data.table::uniqueN(processingGroup[get(peaksNew) %in% TRUE], by = c("Feature_ID"))
  nReplicatesNew <- data.table::uniqueN(processingFeature[color %in% "black"], by = c("Batch"))
  nSeriesNew <- data.table::uniqueN(processingGroup[get(peaksNew) %in% TRUE], by = c("groupIndices"))

  logr::put(paste0("Removed ", nSeriesOld - nSeriesNew, " ", Series, " with less than ", MIN_FEATURE, " Signals."))
  logr::put(paste0("Remaining Data set with ", nCompoundsNew, " ", Compounds," and ", nReplicatesNew, " Batch(es) -> ", nSeriesNew, " ", Series))

  stopifnot(exprs = {
    "all Compounds were removed" = nCompoundsNew  > 0
    "all Dilution/Concentration-Series were removed" = nSeriesNew > 0
  })

  cutoff <- processingFeature[groupIndices %in% processingGroup[get(peaksNew) %in% FALSE, groupIndices]]
  processingFeature <- processingFeature[groupIndices %in% processingGroup[get(peaksNew) %in% TRUE, groupIndices]]

  return(list(processingFeature, cutoff))


}
